### ISSUE TITLE
Important output from stdout disappered for students to understand errors

### ISSUE THREAD

**Issue by igormcoelho** [education/autograding-command-grader#13]
I'm struggling with newer updates here, as the change made my students not to see any output from the commands... so, they cannot know what happened, which unit tests did not pass, even when downloading the logs.
I think a single line could be changed and would fix this...
Some other people are affected too: https://github.com/orgs/community/discussions/89879  (see post from @mikeryu at https://github.com/orgs/community/discussions/89879#discussioncomment-8712292)
I made a prototype of the idea at https://github.com/igormcoelho-learning/autograding-command-grader (tag ~v4~ v6 is working)

Just changed line at `src/main.js`:
```
    // output = execSync(command, {timeout, env}).toString()
    output = execSync(command, {timeout, env, stdio: 'inherit'}).toString()    
```

Please consider adding stdio 'inherit' option as default.

[EDIT] I noticed that `toString()` may break, as this may return null... please consider the following v6 below:

```
    let output_v = execSync(command, {timeout, env, stdio: 'inherit'})
    output = ""
    if(output_v == null) {}
    else {
      output = output_v.toString()
    }
```

This works fine!

**Comment by huichen-cs** [comment]
@igormcoelho 

I am having exactly the same problem. The students can no longer see what test cases are failing, what the expected result should be, and what the actual result their code produces. 

I had to manually place the old workflow files in the students' repositories. I tested your revision, it also works, but it also involves updating the workflow file to use your revision. 

I hope that your suggested change is picked up soon.  Thanks for sharing!

**Comment by igormcoelho** [comment]
> I tested your revision, it works, but it also involves updating the workflow file to use your revision.

Please use version v6 now... I found that v4 had some problems with a `null` in the `execSync` part, but including an if in v6 seemed to solve the issue. You are right, it requires every student to change these lines, I also hope GitHub team adopts this or any other solution officially. 

Thanks for the support!

**Comment by huichen-cs** [comment]
@igormcoelho 

Thank you. Just noticed your made new commits and tags.

**Comment by igormcoelho** [comment]
To demonstrate the difference of behavior from existing one and my proposal, I created two autograding tasks, named "make test" and "echo test", that perform the same thing (a `make test` command on a C++ unit test). The `make test` only shows general "error", and the v6 below on `echo test` shows exactly which tests fail.

![image](https://github.com/education/autograding-command-grader/assets/290989/9f0fc817-21f8-4e2b-acac-7b8ea769b5eb)

on `workflows.yml`, the `make test` is using `      uses: education/autograding-command-grader@v1` and `echo test` is using `      uses: igormcoelho-learning/autograding-command-grader@v6`

In a good case (passing tests), this is what happens:

![image](https://github.com/education/autograding-command-grader/assets/290989/caeeddc0-9e64-45b2-be25-7b139e07568e)

Even when passing, the proposal can also be more informative for students.

**Comment by huichen-cs** [comment]
@igormcoelho 

I think the usefulness is well demonstrated -- we want to give the students feedback, not just a score. 

Perhaps, you want to issue a pull request.  If the pull request is accepted, we don't have to manually update the students' repository to use your revision.  Thanks.

**Comment by igormcoelho** [comment]
> Perhaps, you want to issue a pull request.

Just did it :)

**Comment by huichen-cs** [comment]
@igormcoelho 



> Just did it :)

Thank you, @igormcoelho !

**Comment by KatrinaWright** [comment]
I'm having a similar issue. My students were just automatically migrated from `autograding@v1` to `autograding-grading-reporter@v1` and `autograding-command-grader@v1`, and now our cross-platform bug can't be discovered. It just says "some tests failed" without showing the pytest readout with the failing tests and their output. 

This is the error my students get now: 
![sometestsfailed](https://github.com/education/autograding-command-grader/assets/77311100/d14b9666-a48b-4ce1-8c40-f3083479f5f4)

And this is the error they used to get, which was WAY more useful to the student:
![detailed tests](https://github.com/education/autograding-command-grader/assets/77311100/79bfa3a6-c1ab-4621-81d5-d456c5737592)

Where do I go to update `[.github/workflows/classroom.yml](https://github.com/Joy-of-Coding/arrays-maps-Pavani-Peravali/pull/1/files#diff-4045a417e84764f120c063cd60445b6a057e867d246049365db07a6ea97f655c)` this file for all of my students again so that we can have the prior functionality?

**Comment by igormcoelho** [comment]
@KatrinaWright 
Since GitHub changed the behavior and this PR has not been accepted (yet, I hope), what I'm doing now is the following.
In the README.md of my activity I'm putting the following text:

```
### IMPORTANT
After accepting this activity, you must EDIT the file [.github/workflows/classroom.yml](.github/workflows/classroom.yml) and REPLACE all of the following:
- From: `uses: education/autograding-command-grader@v1`
- To: `uses: igormcoelho-learning/autograding-command-grader@v6`

If you do not change this, the activity will work correctly, but you won't be able to see which errors happened in detail, so please perform the change in the file. There are open discussions in GitHub Community to try to solve this automatically in the future.
Also, please add your full name in the line below:

**STUDENT NAME**:
```

That's how I'm doing for the moment.

Unfortunatelly, we cannot change the workflows file in the template, because it is created automatically by the github classroom activity, so the best way I found was to introduce this explanation in the README and ask the students to do that (or you can manually edit each of their repositories, if they are unable to do that...).

**Comment by ashishkeshan** [comment]
Hello, we just merged in https://github.com/education/autograding-command-grader/pull/15 which shold address this issue. Thanks for bringing it to our attention!

**Comment by igormcoelho** [comment]
Ok, that's a good thing for us all, one big problem is solved. In any case, I think this solution you merged or the one I proposed here introduce the same design flaw: they will permanently disable the `output`, that will **always** be null... or am I wrong? The output is already flushed...
Perhaps the `output` was meant to be used by someone in some future step, so in my opinion a better solution here would be to introduce some FLAG (enabled by default) that will allow the `inherit` mode on stdio, and if someone disables it, then the output is sent through the next phases.
Otherwise it's just better to remove the output from there, but I don't think it was the original design. I'll try to demonstrate that on PR #17 and then you can better evaluate if it's worth or not. Thanks again!

**Comment by KatrinaWright** [comment]
> Hello, we just merged in #15 which should address this issue. Thanks for bringing it to our attention!

This solved the issue for me! My students can now find the online-run pytest results so they can debug cross-platform. Thank you!

**Comment by huichen-cs** [comment]
> Hello, we just merged in #15 which should address this issue. Thanks for bringing it to our attention!

Hello @ashishkeshan 

Thanks for merging this change. It is a great improvement. However, I did notice a change of the behavior and wonder if it could be fixed for educators like me. When a student's code has compilation errors, the education/autograding-grading-reporter@v1 reports the compilation errors. However, when the student comes back to examine it again, such as after refreshing the browser window, the error message is gone, and in fact,  a base64 encoded message is displayed:

```
Run education/autograding-grading-reporter@v1
  with:
    runners: autofeedback-test-suite-01
    token: ***
  env:
    AUTOFEEDBACK-TEST-SUITE-01_RESULTS: eyJ2ZXJzaW9uIjoxLCJzdGF0dXMiOiJmYWlsIiwibWF4X3Njb3JlIjoxMDAsInRlc3RzIjpbeyJuYW1lIjoiQXV0b2ZlZWRiYWNrIFRlc3QgU3VpdGUgMDEiLCJzdGF0dXMiOiJmYWlsIiwic2NvcmUiOjAsIm1lc3NhZ2UiOiJmYWlsZWQgd2l0aCBleGl0IGNvZGUgMSIsInRlc3RfY29kZSI6ImdyYWRsZSB0ZXN0IiwiZmlsZW5hbWUiOiIiLCJsaW5lX25vIjowLCJkdXJhdGlvbiI6MTkzNDJ9XX0=
```
I decoded the base64 encoded message, it is
```
{"version":1,"status":"fail","max_score":100,"tests":[{"name":"Autofeedback Test Suite 01","status":"fail","score":0,"message":"failed with exit code 1","test_code":"gradle test","filename":"","line_no":0,"duration":19342}]}
```
which is, apparently a serialized object. 

I wonder if this is the issue @igormcoelho described in 

> Ok, that's a good thing for us all, one big problem is solved. In any case, I think this solution you merged or the one I > proposed here introduce the same design flaw: they will permanently disable the output, that will always be null... or am I wrong? The output is already flushed...
Perhaps the output was meant to be used by someone in some future step, so in my opinion a better solution here would be to introduce some FLAG (enabled by default) that will allow the inherit mode on stdio, and if someone disables it, then the output is sent through the next phases.
Otherwise it's just better to remove the output from there, but I don't think it was the original design. I'll try to demonstrate that on PR https://github.com/education/autograding-command-grader/pull/17 and then you can better evaluate if it's worth or not. Thanks again!

Hope that your team can look at this.  Some students are truly perplexed by this, and it is an inconvenience to reproduce the same error message offline. Addressing issue is a great help.  Thank you.

**Comment by ashishkeshan** [comment]
@huichen-cs are the compilation errors not visible in the `autograding-command-grader` step? I can take a look as well, thanks for bringing this to my attention.

**Comment by huichen-cs** [comment]
> @huichen-cs are the compilation errors not visible in the `autograding-command-grader` step? I can take a look as well, thanks for bringing this to my attention.

Thank you @ashishkeshan for your quick reply.

It appears the first time. But, when you visit it again, it is replaced by the base64 encoded message (serialized object, I suppose).

**Comment by igormcoelho** [comment]
> I wonder if this is the issue @igormcoelho described in

I don't think it's the same thing... although I had some students this week that showed me some crazy screen results. I could not see that at the time of the class so I asked them to send me by email, which they didn't... so I really don't know. 
It's very strange that the GitHub Action output is not showing the same thing after refresh... shouldn't this information be stored/cached by github action itself?

**Comment by ashishkeshan** [comment]
Are the students looking in the step before the `Autograding Reporter`? On my end I'm still able to see the logs from a test that is a day old. 

![Image](https://github.com/education/autograding-command-grader/assets/17459726/fa020182-4d54-4bab-b1fb-7aeedac92627)

**Comment by huichen-cs** [comment]
> Are the students looking in the step before the `Autograding Reporter`? On my end I'm still able to see the logs from a test that is a day old.

Thank you @ashishkeshan  for your quick reply.

Upon seeing your message, I took a look at it again. I realized that it was subtler than I thought.  First, the students and I were looking in the step before the `Autograding Reporter`. See the screen capture below:

![run-autograding-tests-capture-1](https://github.com/education/autograding-command-grader/assets/13919406/9f8448d3-c072-4651-bfce-32f13f14b6bf)

Second, now I realize that it is subtle. I don't seem to be able to consistently produce it, but it seems when you are on this window and review the results, if you refresh the browser window, the results will be replaced by the base64 encoded message like my screen shot shows. When you are in this state, then when  you return to the screen at a later time, the results persists unless you click at the "run-autograding-tests" again.

**Comment by ashishkeshan** [comment]
@huichen-cs What do the logs look like for the `Autofeedback Test Suite 01`? That may be what you and your students are looking for.

**Comment by huichen-cs** [comment]
@ashishkeshan , I thought I showed the log in the screen shot I shared. Wasn't it the log under " Run education/....@v1"?

**Comment by ashishkeshan** [comment]
If you click into the step above, titled `Autofeedback Test Suite 01`, you should see some logs too.

**Comment by huichen-cs** [comment]
@ashishkeshan ,

I see it now. I missed that. My mistake. Thank you! This is really helpful!

**Comment by ashishkeshan** [comment]
Going to close this out now, if anyone has any other concerns feel free to open up another issue 😄
